/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module Half_Adder(a, b, sum, carry);
  input a;
  wire a;
  input b;
  wire b;
  output carry;
  wire carry;
  output sum;
  wire sum;
  assign carry = a & b;
  assign sum = a ^ b;
endmodule
