/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module encoder_4to2(d, y, valid);
  input [3:0] d;
  wire [3:0] d;
  output valid;
  wire valid;
  output [1:0] y;
  wire [1:0] y;
  assign y[1] = d[2] | d[3];
  assign y[0] = d[1] | d[3];
  assign valid = | d;
endmodule
