/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module decoder_2to4(a, en, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input [1:0] a;
  wire [1:0] a;
  input en;
  wire en;
  output [3:0] y;
  wire [3:0] y;
  assign _00_ = en & a[1];
  assign y[3] = _00_ & a[0];
  assign y[0] = _01_ & _03_;
  assign _01_ = en & _02_;
  assign y[1] = _01_ & a[0];
  assign y[2] = _00_ & _03_;
  assign _02_ = ~ a[1];
  assign _03_ = ~ a[0];
endmodule
