/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module priority_encoder_4to2(d, y, valid);
  wire _00_;
  wire [1:0] _01_;
  wire _02_;
  wire [1:0] _03_;
  wire _04_;
  input [3:0] d;
  wire [3:0] d;
  output valid;
  wire valid;
  output [1:0] y;
  wire [1:0] y;
  assign _04_ = d[0] ? 1'h1 : 1'h0;
  assign _03_ = d[1] ? 2'h1 : 2'h0;
  assign _02_ = d[1] ? 1'h1 : _04_;
  assign _01_ = d[2] ? 2'h2 : _03_;
  assign _00_ = d[2] ? 1'h1 : _02_;
  assign y = d[3] ? 2'h3 : _01_;
  assign valid = d[3] ? 1'h1 : _00_;
endmodule
