/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module mux_4to1(a, b, c, d, sel, y);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  input d;
  wire d;
  input [1:0] sel;
  wire [1:0] sel;
  output y;
  wire y;
  function [0:0] _4_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _4_ = b[0:0];
      4'b??1?:
        _4_ = b[1:1];
      4'b?1??:
        _4_ = b[2:2];
      4'b1???:
        _4_ = b[3:3];
      default:
        _4_ = a;
    endcase
  endfunction
  assign y = _4_(1'hx, { a, b, c, d }, { _3_, _2_, _1_, _0_ });
  assign _0_ = sel == 2'h3;
  assign _1_ = sel == 2'h2;
  assign _2_ = sel == 2'h1;
  assign _3_ = ! sel;
endmodule
