/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module mux_2to1(a, b, sel, y);
  input a;
  wire a;
  input b;
  wire b;
  input sel;
  wire sel;
  output y;
  wire y;
  assign y = sel ? b : a;
endmodule

module mux_4to1_struct(a, b, c, d, sel, y);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  input d;
  wire d;
  input [1:0] sel;
  wire [1:0] sel;
  wire w1;
  wire w2;
  output y;
  wire y;
  mux_2to1 m1 (
    .a(c),
    .b(d),
    .sel(sel[0]),
    .y(w2)
  );
  mux_2to1 m2 (
    .a(w1),
    .b(w2),
    .sel(sel[1]),
    .y(y)
  );
  mux_2to1 mo (
    .a(a),
    .b(b),
    .sel(sel[0]),
    .y(w1)
  );
endmodule
