/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module basic_gate(a, b, y_and, y_or, y_xor, y_xnor, y_nand, y_nor, not_a, not_b);
  input a;
  wire a;
  input b;
  wire b;
  output not_a;
  wire not_a;
  output not_b;
  wire not_b;
  output y_and;
  wire y_and;
  output y_nand;
  wire y_nand;
  output y_nor;
  wire y_nor;
  output y_or;
  wire y_or;
  output y_xnor;
  wire y_xnor;
  output y_xor;
  wire y_xor;
  assign y_nor = ~y_or;
  assign y_nand = ~y_and;
  assign y_xnor = ~y_xor;
  assign not_a = ~a;
  assign not_b = ~b;
  assign y_or = a | b;
  assign y_and = a & b;
  assign y_xor = a ^ b;
endmodule
